"""Generate the MyST API documentation page from package docstrings."""

from __future__ import annotations

import inspect
import sys
import textwrap
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import quickbrain  # noqa: E402
import quickbrain.plotting as plotting  # noqa: E402


PUBLIC_OBJECTS = [
    quickbrain.plot_brain,
    quickbrain.load_example_image,
]


def _clean_doc(obj) -> str:
    doc = inspect.getdoc(obj) or "No docstring available."
    return textwrap.dedent(doc).strip()


def _signature(obj) -> str:
    return f"{obj.__name__}{inspect.signature(obj)}"


def _function_section(obj) -> str:
    return "\n".join(
        [
            f"## `{obj.__name__}`",
            "",
            "```python",
            _signature(obj),
            "```",
            "",
            _clean_doc(obj),
            "",
        ]
    )


def main() -> None:
    output = Path(__file__).with_name("documentation.md")
    sections = [
        "# **quick** API Documentation",
        "",
        "<!-- This file is generated by doc/generate_api_docs.py. -->",
        "",
        _clean_doc(quickbrain),
        "",
        f"## `quickbrain.plotting`",
        "",
        _clean_doc(plotting),
        "",
    ]
    sections.extend(_function_section(obj) for obj in PUBLIC_OBJECTS)
    output.write_text("\n".join(sections), encoding="utf-8")


if __name__ == "__main__":
    main()
